#=================================================
# https://github.com/sidpixel/lede
# Description: Build OpenWrt using GitHub Actions
# Lisence: MIT
# Author: sidpixel
#=================================================

name: 7621 Lienol 
on:
  repository_dispatch:
  workflow_dispatch:

env:
  REPO_URL: https://github.com/Lienol/openwrt
  REPO_BRANCH: 19.07
  RELEASE_VERSION: 19.07
  CONFIG_FILE: 7621.config
  OS_ARCH: Lienol7621

 

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name:  Space cleanup and Initialization environment
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        sudo swapoff /mnt/swapfile
        sudo rm -rf /imagegeneration /opt /mnt/swapfile /usr/local/aws* /usr/local/julia* /usr/share/swift* /usr/share/sbt* /usr/local/share/chromium* /usr/local/share/powershell* 
        docker rmi `docker images -q`
        sudo -E rm -rf /usr/share/dotnet /etc/mysql /etc/php /etc/apt/sources.list.d /usr/local/lib/android
        sudo -E apt-mark hold grub-efi-amd64-signed
        sudo -E apt update
        sudo -E apt -y purge azure-cli* docker* ghc* zulu* llvm* firefox google* dotnet* powershell* openjdk* mysql* php* mongodb* dotnet* snap*
        sudo -E apt -y full-upgrade
        sudo -E apt install build-essential clang flex bison g++ gawk gcc-multilib g++-multilib \
        gettext git libncurses-dev libssl-dev python3-distutils rsync unzip zlib1g-dev \
        file wget python2 gcc
        sudo -E systemctl daemon-reload
        sudo -E apt -y autoremove --purge
        sudo -E apt clean
        sudo -E timedatectl set-timezone "Asia/Shanghai"



    - name: Clone source code
      run: |
        df -hT $PWD
        rm -rf openwrt
        git clone --single-branch  -b $REPO_BRANCH  $REPO_URL openwrt
        echo "FILE_DATE=$(date +%Y%m%d%H%M)" >>"$GITHUB_ENV"


    - name: Load custom feeds and Load custom configuration
      working-directory: ./openwrt
      run: |
        #sed -i '$a src-git kenzo https://github.com/kenzok8/openwrt-packages.git' feeds.conf.default
        #sed -i '$a src-git small https://github.com/kenzok8/small.git' feeds.conf.default
        git clone https://github.com/destan19/OpenAppFilter.git package/OpenAppFilter
        cat feeds.conf.default    

    - name: load the  feeds
      working-directory: ./openwrt
      run: |
        ./scripts/feeds clean 
        ./scripts/feeds update -a
        ./scripts/feeds install -a

    - name: Download package
      working-directory: ./openwrt
      run: |
        sed -i 's/192.168.1.1/10.1.1.1/g' package/base-files/files/bin/config_generate
        mv $GITHUB_WORKSPACE/$CONFIG_FILE  .config
        make defconfig -j$(nproc)
        make download -j$(nproc)

    
    - name: Compile the firmware
      working-directory: ./openwrt
      run: |
        echo -e "$(nproc) thread compile"
        make -j$(nproc) V=s  || make -j1 ||make -j1 V=s
          

    - name: Check space usage
      if: (!cancelled())
      run: df -hT

    - name: Organize files
      run: |
        rm -rf ./artifact/
        mkdir -p ./artifact
        cp -rf $(find openwrt/bin/targets/*/*/  -type f  -name "*mt7621*") artifact/
        cd ./artifact/
        ls -Ahl
        gzip --best *
        ls -Ahl

    - name: Upload firmware directory
      uses: actions/upload-artifact@master
      with:
        name: openwrt-firmware
        path:  artifact/

    - name: Create release
      uses: softprops/action-gh-release@v1
      with:
        tag_name: ${{ env.OS_ARCH }}-${{ env.FILE_DATE }}-${{ env.RELEASE_VERSION }}
        files: artifact/*
