#=================================================
# Description: Build OpenWrt using GitHub Actions
# Lisence: MIT
# Author: eSirPlayground
# Youtube Channel: https://goo.gl/fvkdwm 
#=================================================

name: 8632lienol

on: 
  release:
    types: [published]

  push:
    branches: 
      - master
    paths:
      - 'lenol.config.config'
      - '.github/workflows/8632lienol.yml'
  schedule:
    - cron: '30 4 15 * *'

  #schedule:
  #  - cron: 0 8 * * 5

  #watch:
  #  types: [started]
env:
  DEBIAN_FRONTEND: noninteractive
  REPO_URL: https://github.com/Lienol/openwrt
  REPO_BRANCH: main
  FEEDS_CONF: feeds.conf.default
  CONFIG_FILE: 'x86.config'
  DIY_P1_SH: diy-part1.sh
  DIY_P2_SH: diy-part2.sh

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: Initialization environment and space clean

      run: |
        sudo rm -rf /imagegeneration /opt  /usr/local/aws* /usr/local/julia* /usr/share/swift* /usr/share/sbt* \
        /usr/local/share/chromium* /usr/local/share/powershell* 
        docker rmi `docker images -q`
        sudo -E rm -rf /usr/share/dotnet /etc/mysql /etc/php /etc/apt/sources.list.d /usr/local/lib/android
        sudo -E apt-mark hold grub-efi-amd64-signed
        sudo -E apt-get update 
        sudo -E apt-get -y upgrade
        sudo -E apt-get -y install build-essential asciidoc binutils bzip2 gawk gettext git libncurses5-dev patch unzip \
        lib32gcc-s1 libc6-dev-i386 subversion flex node-uglify gcc-multilib g++-multilib p7zip p7zip-full msmtp libssl-dev \
        texinfo libglib2.0-dev xmlto qemu-utils  libelf-dev autoconf automake libtool autopoint device-tree-compiler \
        libuv1-dev python3.6 zlib1g-dev upx-ucl node-uglify antlr3 gperf wget swig rsync
        sudo -E apt-get -y autoremove --purge
        sudo -E apt-get clean
        echo "FILE_DATE=$(date +%Y%m%d%H%M)" >>"$GITHUB_ENV"


    - name: Clone source code
      run: |
        git clone   -b $REPO_BRANCH $REPO_URL  openwrt
        chmod +x $DIY_P1_SH $DIY_P2_SH
        df -hT

    - name: Update & Install feeds
      working-directory: ./openwrt
      run: |
        $GITHUB_WORKSPACE/$DIY_P1_SH
        $GITHUB_WORKSPACE/$DIY_P2_SH
        ./scripts/feeds update -a
        ./scripts/feeds install -a

    #- name: Import external feeds
    #  working-directory: ./openwrt
    #  run: |
    #    git clone https://github.com/Lienol/openwrt-package package/lienol
    #    git clone "your_github_link" package/"your_folder_name"      

    - name: Configuration Customization - Build_x86
      working-directory: ./openwrt
      run: |
        cat ../$CONFIG_FILE > .config
        make defconfig
        
    - name: Download package
      working-directory: ./openwrt
      run: |
        make download -j$(nproc)
        find dl -size -1024c -exec ls -l {} \;
        find dl -size -1024c -exec rm -f {} \;

    - name: Build firmware
      working-directory: ./openwrt
      run: |
        #make -j8
        make -j$(nproc) V=s  || make -j1 V=s
        
   
    - name : Upload artifact
      uses: actions/upload-artifact@master
      with:
        name: OpenWrt-x86-32
        path: openwrt/bin/targets
        
    - name: Release
      uses: softprops/action-gh-release@v1
      with:
        tag_name: x86lienol-${{ env.FILE_DATE }}
        files: |
          openwrt/bin/targets/x86/generic/openwrt-x86-generic-generic-squashfs-combined-efi.img.gz
          openwrt/bin/targets/x86/generic/openwrt-x86-generic-generic-squashfs-rootfs.img.gz
          openwrt/bin/targets/x86/generic/openwrt-x86-generic-generic.manifest
          
