
#=================================================
# https://github.com/sidpixel/lede
# Description: Build OpenWrt using GitHub Actions
# Lisence: MIT
# Author: sidpixel
#=================================================

name: all firmware intergrate 8632 and 7621 firm

on:
  repository_dispatch:
  workflow_dispatch:
  
jobs: 
  job_build_firmware:
    runs-on: ubuntu-latest

    name: build (${{ matrix.platform }})
    strategy:
      fail-fast: false
      matrix:
        include:  
          - platform: lienol_i386_pentium4
            wheel: true
            config_file: 8632.config
            repo_url: https://github.com/sidpixel/op
            repo_branch: 19.07
            release_version: 19.07
            os_arch: lienol8632
            os_type: x86-generic

          - platform: immort_i386_pentium4
            wheel: true
            config_file: 8632.config
            repo_url: https://github.com/immortalwrt/immortalwrt
            repo_branch: openwrt-18.06
            release_version: 18.06
            os_arch: immort8632
            os_type: x86-generic

          - platform: lienol_7621_clash
            wheel: true
            config_file: 7621clash.config
            repo_url: https://github.com/Lienol/op
            repo_branch: 19.07
            release_version: 19.07
            os_arch: lienol7621-clash
            os_type: mt7621
            
          - platform: lienol_7621_passwall
            wheel: true
            config_file: 7621pw.config
            repo_url: https://github.com/Lienol/op
            repo_branch: 19.07
            release_version: 19.07
            os_arch: lienol7621
            os_type: mt7621

          - platform: immortal_mipsel_7621
            wheel: true
            config_file: 7621pw.config
            repo_url: https://github.com/immortalwrt/immortalwrt
            repo_branch: openwrt-18.06
            release_version: 18.06
            os_arch: immortal7621
            os_type: mt7621

    steps:

    - name: Skip build if wheel is false
      if: matrix.wheel == false
      run:  exit 1
      
    - name: Checkout
      uses: actions/checkout@main
      with:
        fetch-depth: 1
        ref: 'master'
    - name: create my space
      run: |
        sudo rm -rf /mnt/src
        sudo mkdir -p /mnt/src
        sudo chown -R  $USER.$USER  /mnt/src
        df -h  
    - name:  Space cleanup and Initialization environment
      working-directory: /mnt/src
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |       
        sudo -E apt update
        sudo -E apt install build-essential clang flex bison g++ gawk gcc-multilib g++-multilib \
        gettext git libncurses-dev libssl-dev python3-distutils rsync unzip zlib1g-dev \
        file wget python2 gcc
        sudo -E timedatectl set-timezone "Asia/Shanghai"

    - name:  ${{ matrix.platform }} firmware source code download
      working-directory: /mnt/src
      run: |
        git clone --single-branch  -b ${{ matrix.repo_branch }}  ${{ matrix.repo_url }} openwrt
        echo "FILE_DATE=$(date +%Y%m%d%H%M)" >>"$GITHUB_ENV"
        
    - name:  ${{ matrix.platform }} Load custom feeds and Load custom configuration
      working-directory: /mnt/src/openwrt
      run: |
        #sed -i '$a src-git kenzo https://github.com/kenzok8/openwrt-packages' feeds.conf.default
        #sed -i '$a src-git small https://github.com/kenzok8/small' feeds.conf.default
        git clone --single-branch https://github.com/destan19/OpenAppFilter.git package/OpenAppFilter
        git clone --single-branch https://github.com/xiaorouji/openwrt-passwall.git package/openwrt-passwall
        git clone --single-branch  https://github.com/xiaorouji/openwrt-passwall-packages.git  package/passwall-deps       
        git clone --single-branch https://github.com/vernesong/OpenClash.git package/OpenClash
        cat feeds.conf.default     

    - name: ${{ matrix.platform }} load the  feeds
      working-directory: /mnt/src/openwrt
      run: |
        ./scripts/feeds clean 
        ./scripts/feeds update -a
        ./scripts/feeds install -a
        
    - name: ${{ matrix.platform }} clone  golang latest version
      working-directory: /mnt/src/openwrt
      run: |
        rm -rf feeds/packages/lang/golang
        git clone --single-branch https://github.com/sbwml/packages_lang_golang  feeds/packages/lang/golang
    - name: ${{ matrix.platform }} x86 gateway address change
      working-directory: /mnt/src/openwrt
      if: matrix.os_type == 'x86-generic'
      run: |
        sed -i 's/192.168.1.1/10.0.0.1/g' package/base-files/files/bin/config_generate

    - name: ${{ matrix.platform }} ramchips gateway address change
      working-directory: /mnt/src/openwrt
      if: matrix.os_type == 'mt7621'
      run: |
        sed -i 's/192.168.1.1/10.1.1.1/g' package/base-files/files/bin/config_generate
        
    - name: ${{ matrix.platform }} Download package
      working-directory: /mnt/src/openwrt
      run: |
        sed -i 's/OpenWrt/MyOp/g' package/base-files/files/bin/config_generate
        mv $GITHUB_WORKSPACE/${{ matrix.config_file }}  .config
        make defconfig -j$(nproc)
        make download -j$(nproc)
        df -h
    
    - name:  ${{ matrix.platform }} Compile the firmware
      working-directory: /mnt/src/openwrt
      run: |
        echo -e "$(nproc) thread compile"
        make -j$(nproc) || make -j1 ||make -j1 V=s
          
    - name: Check space usage
      working-directory: /mnt/src
      if: (!cancelled())
      run: df -hT

    - name:  ${{ matrix.platform }} Organize files
      working-directory: /mnt/src
      run: |
        rm -rf ./${{ matrix.os_arch }}/
        mkdir -p ${{ matrix.os_arch }}
        cp -rf $(find openwrt/bin/targets/*/*/  -type f  -name *squashfs* -o -name *manifest*)   ${{ matrix.os_arch }}/
        cd ${{ matrix.os_arch }}
        gzip --best *

    - name: Upload firmware directory
      uses: actions/upload-artifact@main
      with:
        name: ${{ matrix.os_arch }}-${{ matrix.release_version }}-firmware
        path: /mnt/src/${{ matrix.os_arch }}/

    - name: Create release
      uses: softprops/action-gh-release@v1
      with:
        tag_name: ${{ matrix.os_arch }}-${{ env.FILE_DATE }}-${{ matrix.release_version }}
        files: /mnt/src/${{ matrix.os_arch }}/*
  
