#=================================================
# https://github.com/sidpixel/lede
# Description: Build OpenWrt using GitHub Actions
# Lisence: MIT
# Author: sidpixel
#=================================================

name: clean workflow


on:
  repository_dispatch:
  workflow_dispatch:
    
jobs:
  cleanup:
    runs-on: ubuntu-latest

    steps:
    - name: Delete old workflow runs
      uses: stefanzweifel/delete-old-actions-runs@v3
      with:
        retention-days: 30  # 删除30天前的工作流运行记录
        allow-failure: true  # 如果某些记录无法删除，继续执行