#=================================================
# Description: Build OpenWrt using GitHub Actions on macOS
# License: MIT
# Author: sidpixel (Modified for macOS)
#=================================================

name: 7621 Lienol on macOS

on:
  repository_dispatch:
  workflow_dispatch:

env:
  REPO_URL: https://github.com/Lienol/openwrt
  REPO_BRANCH: 19.07
  RELEASE_VERSION: 19.07
  CONFIG_FILE: 7621.config
  OS_ARCH: Lienol7621

jobs:
  build:
    runs-on: macos-latest  # Updated to use macOS

    steps:
    - name: Space cleanup and Initialization environment
      run: |
        df -h $PWD
        rm -rf ./*
        df -h $PWD
    - name: Checkout
      uses: actions/checkout@master

    - name: golang Initialization
      run: |
        wget https://go.dev/dl/go1.23.1.darwin-amd64.tar.gz
        sudo rm -rf /usr/local/go && sudo tar -C /usr/local -xzf go1.23.1.darwin-amd64.tar.gz
        sudo ln -s /usr/local/go/bin/go /usr/local/bin/go

    - name: Clone source code
      run: |
        df -h $PWD
        rm -rf openwrt
        git clone --single-branch -b $REPO_BRANCH $REPO_URL openwrt
        echo "FILE_DATE=$(date +%Y%m%d%H%M)" >>"$GITHUB_ENV"

    - name: Load custom feeds and Load custom configuration
      working-directory: ./openwrt
      run: |
        git clone --single-branch https://github.com/destan19/OpenAppFilter.git package/OpenAppFilter
        git clone --single-branch https://github.com/xiaorouji/openwrt-passwall.git package/openwrt-passwall
        git clone --single-branch https://github.com/xiaorouji/openwrt-passwall-packages.git package/passwall-deps
        cat feeds.conf.default

    - name: Load the feeds
      working-directory: ./openwrt
      run: |
        ./scripts/feeds clean 
        ./scripts/feeds update -a
        ./scripts/feeds install -a

    - name: Download package
      working-directory: ./openwrt
      run: |
        sed -i 's/192.168.1.1/10.1.1.1/g' package/base-files/files/bin/config_generate
        mv $GITHUB_WORKSPACE/$CONFIG_FILE .config
        make defconfig -j$(sysctl -n hw.ncpu)
        make download -j$(sysctl -n hw.ncpu)

    - name: Compile the firmware
      working-directory: ./openwrt
      run: |
        echo -e "$(sysctl -n hw.ncpu) thread compile"
        make -j$(sysctl -n hw.ncpu) || make -j1 || make -j1 V=s

    - name: Check space usage
      if: (!cancelled())
      run: df -h

    - name: Organize files
      run: |
        rm -rf ./artifact/
        mkdir -p ./artifact
        cp -rf $(find openwrt/bin/targets/*/*/ -type f -name "*mt7621*") artifact/
        cd ./artifact/
        ls -Ahl
        gzip --best *
        ls -Ahl

    - name: Upload firmware directory
      uses: actions/upload-artifact@master
      with:
        name: openwrt-firmware
        path: artifact/

    - name: Create release
      uses: softprops/action-gh-release@v1
      with:
        tag_name: ${{ env.OS_ARCH }}-${{ env.FILE_DATE }}-${{ env.RELEASE_VERSION }}
        files: artifact/*