#=================================================
# Description: Build OpenWrt using GitHub Actions
# Lisence: MIT
# Author: eSirPlayground
# Youtube Channel: https://goo.gl/fvkdwm 
#=================================================

name: test

on: 
  release:
    types: [published]

  push:
    branches: 
      - master
    paths:
      - '.github/workflows/test.yml'
      - 'test.config'
  schedule:
    - cron: '30 2 15 * *'

  #schedule:
  #  - cron: 0 8 * * 5

  #watch:
  #  types: [started]
env:
  DEBIAN_FRONTEND: noninteractive
  REPO_URL: https://github.com/coolsnowwolf/lede
  #REPO_URL: https://github.com/Lienol/openwrt
  REPO_BRANCH: master
  FEEDS_CONF: feeds.conf.default
  CONFIG_FILE: 'test.config'
  DIY_P1_SH: diy-part1.sh
  DIY_P2_SH: diy-part2.sh

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: Initialization environment and space clean

      run: |
       
        apt list|grep autoconf