#=================================================
# Description: Build OpenWrt using GitHub Actions
# Lisence: MIT
# Author: eSirPlayground
# Youtube Channel: https://goo.gl/fvkdwm 
#=================================================

name: test

on:
  repository_dispatch:
  workflow_dispatch:


env:
  REPO_URL: https://github.com/openwrt/openwrt
  REPO_BRANCH: openwrt-18.06
  RELEASE_VERSION: 18.06
  CONFIG_FILE: x86.config
  OS_ARCH: 8632official


jobs:
  build:
    runs-on: ubuntu-latest

    env:
      HOME: /mnt

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Show custom home directory
      run: |
        echo "Custom HOME directory: $HOME"
        sudo chown -R $USER:$USER /mnt
        mkdir -pv $HOME/.my_custom_folder
        ls -al $HOME
    - name: Show custom home directory
      run: |
        pwd
        ls -alh
        df -hT $PWD
        

