
#=================================================
# https://github.com/sidpixel/lede
# Description: Build OpenWrt using GitHub Actions
# Lisence: MIT
# Author: sidpixel
#=================================================

name: test

on:
  repository_dispatch:
  workflow_dispatch:
  
jobs: 
  job_build_firmware:
    runs-on: ubuntu-latest

    name: build (${{ matrix.platform }})
    strategy:
      fail-fast: false
      matrix:
        include:  
          - platform: lienol_i386_pentium4
            config_file: 8632.config
            repo_url: https://github.com/Lienol/openwrt
            repo_branch: 19.07
            release_version: 19.07
            os_arch: lienol8632
            os_type: x86-generic

          - platform: immort_i386_pentium4
            config_file: 8632.config
            repo_url: https://github.com/immortalwrt/immortalwrt
            repo_branch: openwrt-18.06
            release_version: 18.06
            os_arch: immort8632
            os_type: x86-generic

          - platform: lienol_mipsel_7621
            config_file: 7621.config
            repo_url: https://github.com/Lienol/openwrt
            repo_branch: 19.07
            release_version: 19.07
            os_arch: lienol7621
            os_type: mt7621

          - platform: immortal_mipsel_7621
            config_file: 7621.config
            repo_url: https://github.com/immortalwrt/immortalwrt
            repo_branch: openwrt-18.06
            release_version: 18.06
            os_arch: immortal7621
            os_type: mt7621

    steps:
    - name: Checkout
      uses: actions/checkout@main
      with:
        fetch-depth: 1
        ref: 'master'
    - name: create my space
      run: |
        sudo rm -rf /mnt/src
        sudo mkdir -p /mnt/src
        sudo chown -R  $USER.$USER  /mnt/src
        df -h  
    
    
    - name:  ${{ matrix.platform }} Compile the firmware
      working-directory: /mnt/src/openwrt
      run: |
        mkdir -pv openwrt/bin/gargets/1/1
        touch  openwrt/bin/gargets/1/1/${{ matrix.os_type }}.img
          
    - name: Check space usage
      working-directory: /mnt/src
      if: (!cancelled())
      run: df -hT

    - name:  ${{ matrix.platform }} Organize files
      working-directory: /mnt/src
      run: |
        rm -rf ./${{ matrix.os_arch }}/
        mkdir -p ${{ matrix.os_arch }}
        cp -rf $(find openwrt/bin/targets/*/*/  -type f  -name "*${{ matrix.os_type }}*") ${{ matrix.os_arch }}/
        cd ${{ matrix.os_arch }}
        ls -alh
        gzip --best *
        ls -alh
    - name: Upload firmware directory
      uses: actions/upload-artifact@master
      with:
        name: openwrt-firmware
        path: /mnt/src/${{ matrix.os_arch }}/
    - name: Create release
      uses: softprops/action-gh-release@v1
      with:
        tag_name: ${{ matrix.os_arch }}-${{ env.FILE_DATE }}-${{ matrix.release_version }}
        files: /mnt/src/${{ matrix.os_arch }}/*
