#=================================================
# https://github.com/sidpixel/lede
# Description: Build OpenWrt using GitHub Actions
# Lisence: MIT
# Author: sidpixel
#=================================================

name: test yml
on:
  repository_dispatch:
  workflow_dispatch:



  

env:
  REPO_URL: https://github.com/Lienol/openwrt
  REPO_BRANCH: 19.07
  RELEASE_VERSION: 19.07
  CONFIG_FILE: 7621.config
  OS_ARCH: lienol7621
 

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: create my space
      run: |
        sudo rm -rf /mnt/myspace
        sudo mkdir -p /mnt/myspace
        sudo chown -R  $USER.$USER  /mnt/myspace
        df -h  

    - name:  Space cleanup and Initialization environment
      working-directory: /mnt/myspace
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |       
        sudo add-apt-repository ppa:longsleep/golang-backports
        sudo -E apt update
        sudo -E apt  golang
        sudo -E timedatectl set-timezone "Asia/Shanghai"
    - name: check go version
      working-directory: /mnt/myspace
      run: |
        go version
        apt list|grep golang|grep installed
