#=================================================
# Description: Build OpenWrt using GitHub Actions
# Lisence: MIT
# Author: eSirPlayground
# Youtube Channel: https://goo.gl/fvkdwm 
#=================================================

name: test

on:
  repository_dispatch:
  workflow_dispatch:


env:
  REPO_URL: https://github.com/openwrt/openwrt
  REPO_BRANCH: openwrt-18.06
  RELEASE_VERSION: 18.06
  CONFIG_FILE: x86.config
  OS_ARCH: 8632official


jobs:
  build:
    runs-on: macos-latest
    steps:


    - name: set custom home directory
      run: |
        brew install go
        pwd
        ls -alh
        sudo rm -rf /System/Volumes/Data/*       
        df -h

