#=================================================
# Description: Build OpenWrt using GitHub Actions
# Lisence: MIT
# Author: eSirPlayground
# Youtube Channel: https://goo.gl/fvkdwm 
#=================================================

name: test

on:
  repository_dispatch:
  workflow_dispatch:


env:
  REPO_URL: https://github.com/openwrt/openwrt
  REPO_BRANCH: openwrt-18.06
  RELEASE_VERSION: 18.06
  CONFIG_FILE: x86.config
  OS_ARCH: 8632official


jobs:
  build:
    runs-on: macos-latest

    env:
      HOME: /mnt
      GITHUB_WORKSPACE: /mnt

    steps:


    - name: set custom home directory
      run: |
        go version
        
        

