
#=================================================
# https://github.com/sidpixel/lede
# Description: Build OpenWrt using GitHub Actions
# Lisence: MIT
# Author: sidpixel
#=================================================

name: any test

on:
  repository_dispatch:
  workflow_dispatch:


  
jobs: 
  job_build_firmware:
    runs-on: ubuntu-latest

    name: build (${{ matrix.platform }})
    strategy:
      fail-fast: false
      matrix:
        platform: [immort1806,lienol1907]
        config_file: [8632.config,7621clash.config,7621pw.config]
        include:
          - platform: immort1806
            wheel: true
            repo_url: https://github.com/immortalwrt/immortalwrt
            repo_branch: openwrt-18.06
          - platform: lienol1907
            wheel: true
            repo_url: https://github.com/sidpixel/op
            repo_branch: 19.07
          - config_file: 8632.config
            os_type: x86-generic
            os_arch: x86-generic
          - config_file: 7621clash.config
            os_arch: 7621-clash
            os_type: mt7621
          - config_file: 7621pw.config
            os_arch: 7621-passwall
            os_type: mt7621




    steps:

    - name: Skip build if wheel is false
      if: matrix.wheel == false
      run:  exit 1
      
    - name: Checkout
      uses: actions/checkout@main
      with:
        fetch-depth: 1
        ref: 'master'
    - name: create my space
      run: |
        sudo rm -rf /mnt/src
        sudo mkdir -p /mnt/src/openwrt
        sudo chown -R  $USER.$USER  /mnt/src
        df -h  

 
        
    - name: ${{ matrix.platform }} x86 gateway address change
      working-directory: /mnt/src/openwrt
      if: matrix.os_type == 'x86-generic'
      run: |
        touch 8632blank

    - name: ${{ matrix.platform }} ramchips gateway address change
      working-directory: /mnt/src/openwrt
      if: matrix.os_type == 'mt7621'
      run: |
        touch 7621blank
        
    - name: ${{ matrix.platform }} Download package
      working-directory: /mnt/src/openwrt
      run: |
        mv $GITHUB_WORKSPACE/${{ matrix.config_file }}  ./
        echo "FILE_DATE=$(date +%Y%m%d%H%M)" >>"$GITHUB_ENV"
        
    - name:  ${{ matrix.platform }} Organize files
      working-directory: /mnt/src
      run: |
        mkdir -p  artifact
        cp -a openwrt/*  artifact/
        cd artifact
        gzip --best *

    - name: Upload firmware directory
      uses: actions/upload-artifact@main
      with:
        name: ${{ matrix.os_arch }}-${{ github.run_id }}
        path: /mnt/src/artifact/

    
   