
#=================================================
# https://github.com/sidpixel/lede
# Description: Build OpenWrt using GitHub Actions
# Lisence: MIT
# Author: sidpixel
#=================================================

name: test alpha lienol all firmware build


on:
  repository_dispatch:
  workflow_dispatch:


  
jobs: 
  job_build_firmware:
    #runs-on: ubuntu-latest
    runs-on: ubuntu-22.04
    name: build (${{ matrix.platform }}-${{ matrix.config_file }})
    strategy:
      fail-fast: false
      matrix: 
        config_file: [8632_config,8632pw2_config,7621clash_config,7621pw_config,7621pw2_config]
        include:
          - platform: lienol1907
            repo_url: https://github.com/sidpixel/myrouter
            repo_branch: 19.07
          - config_file: 7621pw_config
            wheel: true
          
            

    steps:
    - name: Skip build if wheel is false
      if: matrix.wheel == false
      run:  exit 1
      
    - name: Checkout
      uses: actions/checkout@main
      with:
        fetch-depth: 1
        ref: 'master'
  

        
    - name: Download package
      if: startwith(matrix.config_file, '8632')
      run: |
        echo  's/192.168.1.1/10.0.0.1/g' > /tmp/host1
 
    - name: Download package
      if: startwith(matrix.config_file, '7621')
      run: |
        echo 's/192.168.1.1/10.1.1.1/g' > /tmp/host2
       
  
    - name:  Compile the firmware
      run: |
        cat /tmp/host1
        cat /tmp/host2
          