#=================================================
# Description: Build OpenWrt using GitHub Actions
# Lisence: MIT
# Author: eSirPlayground
# Youtube Channel: https://goo.gl/fvkdwm 
#=================================================

name: test

on:
  repository_dispatch:
  workflow_dispatch:


env:
  REPO_URL: https://github.com/openwrt/openwrt
  REPO_BRANCH: openwrt-18.06
  RELEASE_VERSION: 18.06
  CONFIG_FILE: x86.config
  OS_ARCH: 8632official

 

jobs:
  build2204:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name:  Space cleanup and Initialization environment
      env:
        DEBIAN_FRONTEND: noninteractive
      run: | 
        ls -alh /mnt/
        echo "below space"
        df -hT
        systemctl status docker 
        systemctl list-units|grep service
        free -m
        echo 3|sudo tee /proc/sys/vm/drop_caches
        free -m

  build2004:
    runs-on: ubuntu-20.04

    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name:  Space cleanup and Initialization environment
      env:
        DEBIAN_FRONTEND: noninteractive
      run: | 
        ls -alh /mnt/
        echo "below space"
        df -hT
        systemctl status docker 
        systemctl list-units|grep service
        free -m
        echo 3|sudo tee /proc/sys/vm/drop_caches
        free -m

        

