#=================================================
# https://github.com/sidpixel/lede
# Description: Build OpenWrt using GitHub Actions
# Lisence: MIT
# Author: sidpixel
#=================================================

name: test yml
on:
  repository_dispatch:
  workflow_dispatch:



  

env:
  REPO_URL: https://github.com/Lienol/openwrt
  REPO_BRANCH: 19.07
  RELEASE_VERSION: 19.07
  CONFIG_FILE: 7621.config
  OS_ARCH: lienol7621
 

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: create my space
      run: |
        sudo rm -rf /mnt/myspace
        sudo mkdir -p /mnt/myspace
        sudo chown -R  $USER.$USER  /mnt/myspace
        df -h  

    - name:  Space cleanup and Initialization environment
      working-directory: /mnt/myspace
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |       
        sudo add-apt-repository ppa:longsleep/golang-backports
        sudo -E apt update
        sudo -E apt install build-essential clang flex bison g++ gawk gcc-multilib g++-multilib \
        gettext git libncurses-dev libssl-dev python3-distutils rsync unzip zlib1g-dev \
        file wget python2 gcc upx-ucl rustc cargo golang-go
        sudo -E timedatectl set-timezone "Asia/Shanghai"

    - name: Clone source code
      working-directory: /mnt/myspace
      run: |
        git clone --single-branch  -b $REPO_BRANCH  $REPO_URL openwrt
        echo "FILE_DATE=$(date +%Y%m%d%H%M)" >>"$GITHUB_ENV"


    - name: Load custom feeds and Load custom configuration
      working-directory: /mnt/myspace/openwrt
      run: |
        #sed -i '$a src-git lienolpkg https://github.com/Lienol/openwrt-packages.git;19.07' feeds.conf.default
        #sed -i '$a src-git lienoluci https://github.com/Lienol/openwrt-luci.git;18.06' feeds.conf.default
        git clone --single-branch https://github.com/destan19/OpenAppFilter.git package/OpenAppFilter
        git clone --single-branch https://github.com/xiaorouji/openwrt-passwall.git package/openwrt-passwall
        git clone --single-branch  https://github.com/xiaorouji/openwrt-passwall-packages.git  package/passwall-deps
        
        cat feeds.conf.default

    - name: load the  feeds
      working-directory: /mnt/myspace/openwrt
      run: |
        ./scripts/feeds clean 
        ./scripts/feeds update -a
        ./scripts/feeds install -a

    - name: Download package
      working-directory: /mnt/myspace/openwrt
      run: |
        sed -i 's/192.168.1.1/10.1.1.1/g' package/base-files/files/bin/config_generate
        mv $GITHUB_WORKSPACE/$CONFIG_FILE  .config
        make defconfig -j$(nproc)
        make download -j$(nproc)
        df -h

    
    - name: Compile the firmware
      working-directory: /mnt/myspace/openwrt
      run: |
        echo -e "$(nproc) thread compile"
        make -j$(nproc) || make -j1 ||make -j1 V=s
          

    - name: Check space usage
      working-directory: /mnt/myspace
      if: (!cancelled())
      run: df -hT

    - name: Organize files
      working-directory: /mnt/myspace
      run: |
        rm -rf ./artifact/
        mkdir -p artifact
        cp -rf $(find openwrt/bin/targets/*/*/  -type f  -name "*mt7621*") artifact/
        cd ./artifact/
        ls -Ahl
        gzip --best *
        ls -Ahl

    - name: Upload firmware directory
      uses: actions/upload-artifact@master
      with:
        name: openwrt-firmware
        path: /mnt/myspace/artifact/

    - name: Create release
      uses: softprops/action-gh-release@v1
      with:
        tag_name: ${{ env.OS_ARCH }}-${{ env.FILE_DATE }}-${{ env.RELEASE_VERSION }}
        files: /mnt/myspace/artifact/*
