#=================================================
# Description: Build OpenWrt using GitHub Actions
# Lisence: MIT
# Author: eSirPlayground
# Youtube Channel: https://goo.gl/fvkdwm 
#=================================================

name: test

on:
  repository_dispatch:
  workflow_dispatch:


env:
  REPO_URL: https://github.com/openwrt/openwrt
  REPO_BRANCH: openwrt-18.06
  RELEASE_VERSION: 18.06
  CONFIG_FILE: x86.config
  OS_ARCH: 8632official


jobs:
  build:
    runs-on: ubuntu-latest

    env:
      HOME: /mnt
      GITHUB_WORKSPACE: /mnt

    steps:


    - name: set custom home directory
      run: |
        sudo chown -R $USER:$USER /mnt
        apt list|grep golang-go
        sudo apt-get  install golang-go
        go install golang.org/x/lint/golint@latest
        go install golang.org/x/tools/gopls@latest

    - name: Show custom home directory
      run: |
        pwd
        ls -alh
        df -hT $PWD
        apt list|grep golang-go

    - name: Checkout code
      uses: actions/checkout@v3
        

