#=================================================
# Description: Build OpenWrt using GitHub Actions
# Lisence: MIT
# Author: eSirPlayground
# Youtube Channel: https://goo.gl/fvkdwm 
#=================================================

name: test

on:
  repository_dispatch:
  workflow_dispatch:


env:
  REPO_URL: https://github.com/openwrt/openwrt
  REPO_BRANCH: openwrt-18.06
  RELEASE_VERSION: 18.06
  CONFIG_FILE: x86.config
  OS_ARCH: 8632official

 

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name:  Space cleanup and Initialization environment
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        sudo apt list|grep python2
        sudo -E apt install build-essential clang flex bison g++ gawk gcc-multilib g++-multilib \
        gettext git libncurses-dev libssl-dev python3-distutils rsync unzip zlib1g-dev \
        file wget gcc g++ python2
        sudo -E apt clean
        sudo -E timedatectl set-timezone "Asia/Shanghai"



    - name: Clone source code
      run: |
        df -hT $PWD
        rm -rf openwrt
        git clone --single-branch  -b $REPO_BRANCH  $REPO_URL openwrt
        echo "FILE_DATE=$(date +%Y%m%d%H%M)" >>"$GITHUB_ENV"


    - name: Load custom feeds and Load custom configuration
      working-directory: ./openwrt
      run: |
        sed -i '$a src-git kenzo https://github.com/kenzok8/openwrt-packages' feeds.conf.default
        sed -i '$a src-git small https://github.com/kenzok8/small' feeds.conf.default
        git clone https://github.com/destan19/OpenAppFilter.git package/OpenAppFilter
        cat feeds.conf.default    

    - name: load the  feeds
      working-directory: ./openwrt
      run: |
        ./scripts/feeds clean 
        ./scripts/feeds update -a
        ./scripts/feeds install -a

    - name: Download package
      working-directory: ./openwrt
      run: |
        sed -i 's/192.168.1.1/10.0.0.1/g' package/base-files/files/bin/config_generate
        mv $GITHUB_WORKSPACE/$CONFIG_FILE  .config
        make defconfig -j$(nproc)
        make download -j$(nproc)

    
    - name: Compile the firmware
      working-directory: ./openwrt
      run: |
        echo -e "$(nproc) thread compile"
        make -j$(nproc)  || make -j1 ||make -j1 V=s
          

    - name: Check space usage
      if: (!cancelled())
      run: df -hT

    - name: Organize files
      run: |
        rm -rf ./artifact/
        mkdir -p ./artifact
        cp -rf $(find openwrt/bin/targets/*/*/  -type f  -name "*x86-generic*") artifact/
        cd ./artifact/
        ls -Ahl
        gzip --best *
        ls -Ahl

    - name: Upload firmware directory
      uses: actions/upload-artifact@master
      with:
        name: openwrt-firmware
        path:  artifact/

    - name: Create release
      uses: softprops/action-gh-release@v1
      with:
        tag_name: ${{ env.OS_ARCH }}-${{ env.FILE_DATE }}-${{ env.RELEASE_VERSION }}
        files: artifact/*