
#=================================================
# https://github.com/sidpixel/lede
# Description: Build OpenWrt using GitHub Actions
# Lisence: MIT
# Author: sidpixel
#=================================================

name: test lienol all firmware build


on:
  repository_dispatch:
  workflow_dispatch:


  
jobs: 
  job_build_firmware:
    #runs-on: ubuntu-latest
    runs-on: ubuntu-22.04
    name: build (${{ matrix.platform }}-${{ matrix.config_file }})
    strategy:
      fail-fast: false
      matrix: 
        config_file: [x8664_config,x8632_config,x8632pw2_config,7621clash_config,7621pw_config,7621pw2_config]
        include:
          - platform: lienol1907
            repo_url: https://github.com/sidpixel/op
            repo_branch: 19.07
          - config_file: x8632_config

        exclude:
          - config_file: x8632pw2_config
          - config_file: 7621pw_config
          - config_file: 7621pw2_config
          - config_file: x8664_config
          - config_file: 7621clash_config



                  
    steps: 
    - name: Checkout
      uses: actions/checkout@main
      with:
        fetch-depth: 1
        ref: 'master'
    - name: create my space
      run: |
        sudo rm -rf /mnt/src
        sudo mkdir -p /mnt/src
        sudo chown -R  $USER.$USER  /mnt/src
        df -h  
    - name: Detect Ubuntu version
      id: detect_os
      run: |
        echo "UBUNTU_VERSION=$(lsb_release -rs)" >> $GITHUB_OUTPUT
    - name: ubuntu 22.04 install  dependents pkg 
      env:
        DEBIAN_FRONTEND: noninteractive
      if: steps.detect_os.outputs.UBUNTU_VERSION == '22.04'
      run: |
        sudo -E apt update
        sudo -E apt install build-essential clang flex bison g++ gawk gcc-multilib g++-multilib \
        gettext git libncurses-dev libssl-dev python3-distutils rsync unzip zlib1g-dev \
        file wget python2 gcc libfuse-dev
        sudo -E timedatectl set-timezone "Asia/Shanghai"

    - name: ubuntu 24.04 install  dependents pkg and compile  python2
      env:
        DEBIAN_FRONTEND: noninteractive
      if: steps.detect_os.outputs.UBUNTU_VERSION == '24.04'
      run: |
        sudo -E apt update
        sudo -E apt install build-essential clang flex bison g++ gawk gcc-multilib g++-multilib \
        gettext git libncurses-dev libssl-dev  rsync unzip zlib1g-dev \
        file wget  gcc libfuse-dev       
        sudo wget https://www.python.org/ftp/python/2.7.18/Python-2.7.18.tgz
        sudo tar xzf Python-2.7.18.tgz
        cd Python-2.7.18
        sudo ./configure --prefix=/opt/python2
        sudo make -j$(nproc)
        sudo make install
        sudo ln -s /opt/python2/bin/python2 /usr/local/bin/python2

    - name:  firmware source code download
      working-directory: /mnt/src
      run: |
        git clone --single-branch  -b ${{ matrix.repo_branch }}  ${{ matrix.repo_url }} openwrt
        echo "FILE_DATE=$(date +%Y%m%d%H%M)" >>"$GITHUB_ENV"
        
    - name:  Load custom feeds and Load custom configuration
      working-directory: /mnt/src/openwrt
      run: |
        git clone --depth 1 --single-branch  https://github.com/destan19/OpenAppFilter.git package/OpenAppFilter
        #git clone   -b v5.0.2 --depth 1 --single-branch  https://github.com/destan19/OpenAppFilter.git package/OpenAppFilter
        git clone --depth 1 --single-branch https://github.com/xiaorouji/openwrt-passwall.git package/openwrt-passwall
        git clone --depth 1 --single-branch https://github.com/xiaorouji/openwrt-passwall2.git package/openwrt-passwall2
        git clone --depth 1 --single-branch  https://github.com/xiaorouji/openwrt-passwall-packages.git  package/passwall-deps       
        git clone --depth 1 --single-branch https://github.com/vernesong/OpenClash.git package/OpenClash
        git clone -b lua  --depth 1 --single-branch https://github.com/sbwml/luci-app-alist package/alist
        git clone --depth 1 --single-branch  https://github.com/UnblockNeteaseMusic/luci-app-unblockneteasemusic.git  package/unblockneteasemusic
        git clone --depth 1 --single-branch  https://github.com/kuoruan/openwrt-frp.git package/frp
        
        #git clone --single-branch -b master  https://github.com/cnsilvan/luci-app-unblockneteasemusic.git package/unblockneteasemusic
        
        cat feeds.conf.default     

    - name: load the  feeds
      working-directory: /mnt/src/openwrt
      run: |
        ./scripts/feeds clean 
        ./scripts/feeds update -a
        ./scripts/feeds install -a
        
    - name: config x86 gateway
      working-directory: /mnt/src/openwrt
      if: contains(matrix.config_file, 'x86')
      run: |
        sed -i 's/192.168.1.1/10.0.0.1/g' package/base-files/files/bin/config_generate
    - name: config 7621 gateway
      working-directory: /mnt/src/openwrt
      if: contains(matrix.config_file, '7621')
      run: |
        sed -i 's/192.168.1.1/10.1.1.1/g' package/base-files/files/bin/config_generate

    - name: Download package
      working-directory: /mnt/src/openwrt
      run: |
        sed -i 's/OpenWrt/MyOp/g' package/base-files/files/bin/config_generate
        mv $GITHUB_WORKSPACE/${{ matrix.config_file }}  .config
        make defconfig -j$(nproc)
        cat .config
       

    - name:  Organize files
      working-directory: /mnt/src
      run: |
        set -e  # 一旦出错立即退出

        rm -rf artifact
        mkdir -p artifact
        cp /mnt/src/openwrt/.config artifact/8632config

        
    - name: Upload firmware directory
      uses: actions/upload-artifact@main
      with:
        name: ${{ matrix.platform }}-${{ matrix.config_file }}
        path: /mnt/src/artifact/

    - name: Create release
      uses: softprops/action-gh-release@v1
      with:
        tag_name: ${{ matrix.platform }}-${{ matrix.config_file }}-${{ env.FILE_DATE }}
        #tag_name: ${{ matrix.platform }}-${{ matrix.config_file }}
        files: /mnt/src/artifact/*
